[build]
  command = "npm run build"
  publish = ".next"

[[redirects]]
  from = "/p/*"
  to = "https://writing.alteredcraft.com/p/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/i/*"
  to = "https://writing.alteredcraft.com/i/:splat"
  status = 301
  force = true
